//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperStoreWPF.StoreService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StoreService.IStoreService")]
    public interface IStoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/GetStock", ReplyAction="http://tempuri.org/IStoreService/GetStockResponse")]
        System.Collections.Generic.Dictionary<SuperStoreWebService2.Product, int> GetStock();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/GetStock", ReplyAction="http://tempuri.org/IStoreService/GetStockResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<SuperStoreWebService2.Product, int>> GetStockAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/HandleTransaction", ReplyAction="http://tempuri.org/IStoreService/HandleTransactionResponse")]
        void HandleTransaction(System.Collections.Generic.Dictionary<SuperStoreWebService2.Product, int> transactionDetails, SuperStoreWebService2.Customer buyer, double transactionAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/HandleTransaction", ReplyAction="http://tempuri.org/IStoreService/HandleTransactionResponse")]
        System.Threading.Tasks.Task HandleTransactionAsync(System.Collections.Generic.Dictionary<SuperStoreWebService2.Product, int> transactionDetails, SuperStoreWebService2.Customer buyer, double transactionAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/AddProductToDatabase", ReplyAction="http://tempuri.org/IStoreService/AddProductToDatabaseResponse")]
        void AddProductToDatabase(SuperStoreWebService2.Product p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/AddProductToDatabase", ReplyAction="http://tempuri.org/IStoreService/AddProductToDatabaseResponse")]
        System.Threading.Tasks.Task AddProductToDatabaseAsync(SuperStoreWebService2.Product p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreServiceChannel : SuperStoreWPF.StoreService.IStoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreServiceClient : System.ServiceModel.ClientBase<SuperStoreWPF.StoreService.IStoreService>, SuperStoreWPF.StoreService.IStoreService {
        
        public StoreServiceClient() {
        }
        
        public StoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<SuperStoreWebService2.Product, int> GetStock() {
            return base.Channel.GetStock();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<SuperStoreWebService2.Product, int>> GetStockAsync() {
            return base.Channel.GetStockAsync();
        }
        
        public void HandleTransaction(System.Collections.Generic.Dictionary<SuperStoreWebService2.Product, int> transactionDetails, SuperStoreWebService2.Customer buyer, double transactionAmount) {
            base.Channel.HandleTransaction(transactionDetails, buyer, transactionAmount);
        }
        
        public System.Threading.Tasks.Task HandleTransactionAsync(System.Collections.Generic.Dictionary<SuperStoreWebService2.Product, int> transactionDetails, SuperStoreWebService2.Customer buyer, double transactionAmount) {
            return base.Channel.HandleTransactionAsync(transactionDetails, buyer, transactionAmount);
        }
        
        public void AddProductToDatabase(SuperStoreWebService2.Product p) {
            base.Channel.AddProductToDatabase(p);
        }
        
        public System.Threading.Tasks.Task AddProductToDatabaseAsync(SuperStoreWebService2.Product p) {
            return base.Channel.AddProductToDatabaseAsync(p);
        }
    }
}
